"""Explicit limitation states."""
from enum import Enum


class LimitationState(str, Enum):
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNSUPPORTED_STRUCTURE = "UNSUPPORTED_STRUCTURE"
    NUMERICAL_INSTABILITY = "NUMERICAL_INSTABILITY"
    INVALID_COSMOLOGY = "INVALID_COSMOLOGY"
    IMPOSSIBLE_HIERARCHY = "IMPOSSIBLE_HIERARCHY"
    INCOMPATIBLE_FRAMES = "INCOMPATIBLE_FRAMES"
    UNAVAILABLE_OBSERVATION = "UNAVAILABLE_OBSERVATION"
    OUTSIDE_VALID_RANGE = "OUTSIDE_VALID_RANGE"
